version: "3.9"

services:
  web:
    container_name: server-dev
    image: server-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - server-network
    env_file:
      - docker.env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    command: npm run start:debug
    #command: '/bin/sh -c "echo JWT_SECRET IS $$JWT_SECRET"'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.0
    container_name: server-mongodb
    networks:
      - server-network
    user: mongodb
    ports:
      - 27017:27017
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    restart: unless-stopped
networks:
  server-network:
